# Generated by Django 5.0.6 on 2024-06-26 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('pipeline', '0002_remove_pipeline_image_apikey_embeddingconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestep',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='pipelinestep',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='embeddingconfig',
            name='local_embedding',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='local_model',
        ),
        migrations.AddField(
            model_name='embeddingconfig',
            name='api_key',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='api_key',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SimplePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('variable', models.CharField(max_length=255)),
                ('config', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipelineconfig')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledge')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline.pipeline')),
            ],
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.DeleteModel(
            name='PipelineStep',
        ),
    ]
