# Generated by Django 5.0.6 on 2024-06-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('pipeline', '0003_remove_pipelinestep_knowledge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineconfig',
            old_name='hybrid_search',
            new_name='search_method',
        ),
        migrations.RemoveField(
            model_name='embeddingconfig',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='pipeline_type',
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='rerank',
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='embedding_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='pipeline.embeddingconfig'),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='pipeline.modelconfig'),
        ),
        migrations.RemoveField(
            model_name='simplepipeline',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='simplepipeline',
            name='knowledge',
            field=models.ManyToManyField(blank=True, related_name='simple_pipelines', to='knowledge.knowledge'),
        ),
    ]
