# Generated by Django 5.0.6 on 2024-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_rename_hybrid_search_pipelineconfig_search_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfig',
            name='search_method',
            field=models.CharField(default='knn', max_length=255),
        ),
    ]
