# Generated by Django 5.0.6 on 2024-06-27 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.CharField(default='embed-multilingual-v3.0', max_length=255)),
                ('embedding_size', models.IntegerField(default=1024)),
                ('api_key', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='command-r', max_length=255)),
                ('temperature', models.FloatField(default=0.2)),
                ('chunk_size', models.IntegerField(default=512)),
                ('api_key', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_k', models.IntegerField(default=0)),
                ('search_method', models.CharField(default='knn', max_length=255)),
                ('use_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='pipeline.embeddingconfig')),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='pipeline.modelconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('variable', models.CharField(max_length=255)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipelineconfig')),
                ('knowledge', models.ManyToManyField(blank=True, related_name='knowledge', to='knowledge.knowledge')),
                ('pipeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='pipeline.pipeline')),
            ],
        ),
    ]
