# Generated by Django 5.0.6 on 2024-07-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
