# Generated by Django 5.0.6 on 2024-07-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_pipeline_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
            ],
        ),
    ]
