# Generated by Django 5.0.6 on 2024-07-23 13:40
import random

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('pipeline', '0012_pipelineprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGRetrieverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohere_model', models.CharField(choices=[('cohere', 'Cohere'), ('anthropic', 'Anthropic'), ('gpt', 'GPT'), ('huggingface', 'HuggingFace')], default='cohere', max_length=50)),
                ('cohere_model_name', models.CharField(default='command-r', max_length=100)),
                ('cohere_temperature', models.FloatField(default=0.2)),
                ('rag_preamble', models.TextField(default="\n        Vous êtes un assistant pour les tâches d'assistance technique. \n        Utilisez les éléments de contexte récupérés et les exemples fournis pour répondre \n        à la question. Si vous ne connaissez pas la réponse, dites-le. \n        Utilisez trois phrases maximum et gardez la réponse concise. \n        Répondez toujours en français.\n    ")),
                ('grad_preamble', models.TextField(default="\n        Vous êtes un évaluateur évaluant la pertinence d'un document récupéré par rapport à une question d'utilisateur. \n        Si le document contient des mots-clés ou une signification sémantique liés à la question de l'utilisateur, évaluez-le comme pertinent. \n        Donnez une note binaire 'yes' ou 'no' pour indiquer si le document est pertinent par rapport à la question.\n    ")),
                ('grad_prompt', models.TextField(default="Document récupéré : \n\n {document} \n\n Question de l'utilisateur : {question}")),
                ('route_preamble', models.TextField(default="\n        Prendre en compte l'historique de la conversation. Vous êtes un expert en routage de questions utilisateur vers un vectorstore ou une recherche Web.\n        Le vectorstore contient des documents liés aux agents, à l'ingénierie des invites et aux attaques adversariales.\n        Utilisez le vectorstore pour les questions sur ces sujets. Sinon, utilisez la recherche Web.\n    ")),
                ('history_prompt', models.TextField(default="\n        Étant donné un historique de conversation et la dernière question de l'utilisateur qui pourrait se référer au contexte de l'historique de conversation,\n        formulez une question autonome qui peut être comprise sans l'historique de conversation. \n        Ne répondez PAS à la question, reformulez-la seulement si nécessaire et sinon, renvoyez-la telle quelle.\n    ")),
                ('hallucination_preamble', models.TextField(default="\n        Vous êtes un évaluateur évaluant si une génération LLM est fondée sur / soutenue par un ensemble de faits récupérés. \n        Donnez une note binaire 'yes' ou 'no'. 'yes' signifie que la réponse est fondée sur / soutenue par l'ensemble des faits.\n    ")),
                ('hallucination_prompt', models.TextField(default='Ensemble de faits : \n\n {documents} \n\n Génération LLM : {generation}')),
                ('embedding_type', models.CharField(choices=[('cohere', 'Cohere'), ('gpt', 'GPT'), ('claude', 'Claude'), ('huggingface', 'HuggingFace')], default='cohere', max_length=50)),
                ('embedding_model', models.CharField(default='embed-multilingual-v3.0', max_length=100)),
                ('answer_preamble', models.TextField(default="\n        Vous êtes un évaluateur évaluant si une réponse répond / résout une question \n        Donnez une note binaire 'yes' ou 'no'. 'yes' signifie que la réponse résout la question.\n    ")),
                ('answer_prompt', models.TextField(default="Question de l'utilisateur : \n\n {question} \n\n Génération LLM : {generation}")),
                ('ocr_url', models.URLField(default='https://api.llamacloud.ai/v1/pdf-extract')),
                ('ocr_api_key', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'RAG Retriever Configuration',
                'verbose_name_plural': 'RAG Retriever Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='embedding_config',
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='simplepipeline',
            name='config',
        ),
        migrations.RemoveField(
            model_name='simplepipeline',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='simplepipeline',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='knowledge',
            field=models.ManyToManyField(to='knowledge.knowledge'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.ragretrieverconfig'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmbeddingConfig',
        ),
        migrations.DeleteModel(
            name='ModelConfig',
        ),
        migrations.DeleteModel(
            name='PipelineConfig',
        ),
        migrations.DeleteModel(
            name='SimplePipeline',
        ),
    ]
