# Generated by Django 5.0.6 on 2024-07-24 08:58

import django.db.models.deletion
import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_ragretrieverconfig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='embedding_type',
            new_name='embedding_provider',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='grad_preamble',
            new_name='grade_preamble',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='grad_prompt',
            new_name='grade_prompt',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='cohere_model',
            new_name='llm_provider',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='cohere_model_name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='rag_preamble',
            new_name='model_preamble',
        ),
        migrations.RenameField(
            model_name='ragretrieverconfig',
            old_name='route_preamble',
            new_name='route_question_preamble',
        ),
        migrations.RemoveField(
            model_name='ragretrieverconfig',
            name='cohere_temperature',
        ),
        migrations.RemoveField(
            model_name='ragretrieverconfig',
            name='history_prompt',
        ),
        migrations.AddField(
            model_name='ragretrieverconfig',
            name='embedding_args',
            field=models.JSONField(default=pipeline.models.default_args),
        ),
        migrations.AddField(
            model_name='ragretrieverconfig',
            name='enable_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=models.CharField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1', max_length=120),
        ),
        migrations.AddField(
            model_name='ragretrieverconfig',
            name='model_args',
            field=models.JSONField(default=pipeline.models.default_args),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='config',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.ragretrieverconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=models.CharField(default='llx-3pchZiHONc25URdAcljgWpToR5aykmaBtGjEP8vzTkw6qUI3', max_length=100),
        ),
    ]
