# Generated by Django 5.0.6 on 2024-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_rename_embedding_type_ragretrieverconfig_embedding_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=models.CharField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1', max_length=120),
        ),
    ]
