# Generated by Django 5.0.6 on 2024-07-29 10:57

import pipeline.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_ragretrieverconfig_embedding_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=pipeline.models.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=pipeline.models.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=pipeline.models.EncryptedTextField(default=None),
        ),
    ]
