# Generated by Django 5.0.6 on 2024-07-29 12:53

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_alter_ragretrieverconfig_ocr_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
