# Generated by Django 5.0.6 on 2024-07-29 12:55

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_alter_ragretrieverconfig_embedding_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=fernet_fields.fields.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=fernet_fields.fields.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=fernet_fields.fields.EncryptedTextField(default='ttt', verbose_name='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
            preserve_default=False,
        ),
    ]
