# Generated by Django 5.0.6 on 2024-07-29 13:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0019_alter_ragretrieverconfig_embedding_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1'),
        ),
    ]
