# Generated by Django 5.0.6 on 2024-08-05 10:49

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_alter_ragretrieverconfig_embedding_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='oQS6RB7ImbIe5VY7j23ts5uk7ZBN5ZzP1QYdg0qt'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_provider',
            field=models.CharField(choices=[('cohere', 'Cohere'), ('gpt', 'GPT'), ('claude', 'Claude'), ('ollama', 'Ollama')], default='cohere', max_length=50),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='llm_provider',
            field=models.CharField(choices=[('cohere', 'Cohere'), ('anthropic', 'Anthropic'), ('gpt', 'GPT'), ('ollama', 'Ollama')], default='cohere', max_length=50),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='oQS6RB7ImbIe5VY7j23ts5uk7ZBN5ZzP1QYdg0qt'),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(default='oQS6RB7ImbIe5VY7j23ts5uk7ZBN5ZzP1QYdg0qt'),
        ),
    ]
