# Generated by Django 5.0.6 on 2024-08-05 14:35

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0021_alter_ragretrieverconfig_embedding_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='oQS6RB7ImbIe5VY7j23ts5uk7ZBN5ZzP1QYdg0qt', null=True),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='oQS6RB7ImbIe5VY7j23ts5uk7ZBN5ZzP1QYdg0qt', null=True),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='ocr_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='llx-3pchZiHONc25URdAcljgWpToR5aykmaBtGjEP8vzTkw6qUI3', null=True),
        ),
    ]
