# Generated by Django 5.0.6 on 2025-01-26 19:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0022_alter_ragretrieverconfig_embedding_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='embedding_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1', null=True),
        ),
        migrations.AlterField(
            model_name='ragretrieverconfig',
            name='model_api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='9gGgTTVt7EpV6ufyGkYocXz11V64d4VLWpE7FnR1', null=True),
        ),
    ]
