version: '3.9'

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    ports:
      - "8081:8081"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
      ASYNC_INDEXING: 'true'

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_PASSWORD: NVsM2R8gF0Z5
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

#  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - cache
#    environment:
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_NAME=chatbot_db
#      - DB_USER=postgres
#      - DB_PASSWORD=NVsM2R8gF0Z5
#      - REDIS_HOST=cache
#      - REDIS_PORT=6379
#      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#
volumes:
  weaviate_data:
    driver: local
  db_data:
    driver: local
  cache:
    driver: local
