# Generated by Django 5.0.4 on 2024-05-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='related_issue',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='related_knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_knowledge_bases', to='knowledge_base.knowledgebase'),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
