# Generated by Django 5.0.4 on 2024-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_remove_knowledgebase_related_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='knowledge_base.tag'),
        ),
    ]
