# Generated by Django 5.0.4 on 2024-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_knowledgebase_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
