# Generated by Django 5.0.6 on 2024-07-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('pipeline', '0012_pipelineprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='pipeline.pipeline'),
        ),
    ]
