"""
Django settings for chat_bot project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.core.management.utils import get_random_secret_key
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
import os
from dotenv import load_dotenv

load_dotenv()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('ENCRYPTION_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.1.29", "192.168.101.65", "localhost", "localhost:11434"]

# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users.apps.UsersConfig",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'channels',
    "chat.apps.ChatConfig",
    "knowledge_base.apps.BotKbConfig",
    'rest_framework',
    "rest_framework_api_key",
    "pipeline.apps.PipelineConfig",
    "knowledge.apps.KnowledgeConfig",
    "django_select2",
    'langserve',
    'corsheaders',
    'flat_json_widget',
    "encrypted_model_fields"

    # "react",
    # "django_vite_plugin",
    # "better_json_widget"
    # "django_vite"
    # "rest_framework_simple_api_key",

    # 'compressor',
    # 'django_email_verification',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
DJANGO_VITE = {
    "default": {
        "dev_mode": True,

    }
}

REACT = {
    'RENDER': DEBUG,
    'RENDER_URL': 'http://127.0.0.1:9009/render',
}

FIELD_ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', '')

AUTHENTICATION_BACKENDS = [
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

ASGI_APPLICATION = "chat_bot.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@127.0.0.1:6379/0"],
        },
    },
}

WEAVIA_HOST = "localhost"
WEAVIA_PORT = 8081
COHERE_API_KEY = os.getenv('COHERE_API_KEY')
SITE_ID = 1
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
SOCIALACCOUNT_LOGIN_ON_GET = True
# TODO: change  email
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET'),
            'key': ''

        }
    }
}



ROOT_URLCONF = 'chat_bot.urls'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('PASSWORD')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat_bot.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
POSTGRESS_DB_URI = 'postgresql://postgres:|cT:GVK<o<]9PRX10r":@localhost:5432/postgres?sslmode=disable'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'chatbot_db',
        'USER': 'postgres',
        'PASSWORD': 'NVsM2R8gF0Z5',
        'HOST': 'localhost',

    }
}

# settings.py

CELERY_BROKER_URL = 'redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@localhost:6379',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / "media"
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
    os.path.join(BASE_DIR, 'static/media/'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
COMPRESS_ROOT = BASE_DIR / 'static'

###############################################

# def email_verified_callback(user):
#     user.is_active = True
#
#
# def password_change_callback(user, password):
#     user.set_password(password)
#
# # Global Package Settings
# EMAIL_FROM_ADDRESS = 'noreply@test.com'  # mandatory
# EMAIL_PAGE_DOMAIN = 'localhost:8000'  # mandatory (unless you use a custom link)
# EMAIL_MULTI_USER = False  # optional (defaults to False)
#
# # Email Verification Settings (mandatory for email sending)
# EMAIL_MAIL_SUBJECT = 'Confirm your email {{ user.username }}'
# EMAIL_MAIL_HTML = 'mail_body.html'
# EMAIL_MAIL_PLAIN = 'mail_body.txt'
# EMAIL_MAIL_TOKEN_LIFE = 60 * 60  # one hour
#
# # Email Verification Settings (mandatory for builtin view)
# EMAIL_MAIL_PAGE_TEMPLATE = 'email_success_template.html'
# EMAIL_MAIL_CALLBACK = email_verified_callback
#
# # Password Recovery Settings (mandatory for email sending)
# EMAIL_PASSWORD_SUBJECT = 'Change your password {{ user.username }}'
# EMAIL_PASSWORD_HTML = 'users/password_body.html'
# EMAIL_PASSWORD_PLAIN = 'users/password_body.txt'
# EMAIL_PASSWORD_TOKEN_LIFE = 60 * 10  # 10 minutes
#
# # Password Recovery Settings (mandatory for builtin view)
# EMAIL_PASSWORD_PAGE_TEMPLATE = 'password_changed_template.html'
# EMAIL_PASSWORD_CHANGE_PAGE_TEMPLATE = 'password_change_template.html'
# EMAIL_PASSWORD_CALLBACK = password_change_callback
